"""Added userid

Revision ID: b57bbce81ec8
Revises: 9873097c9701
Create Date: 2023-03-31 20:23:14.212086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57bbce81ec8'
down_revision = '9873097c9701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resume', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_column('resume', 'user_id')
    # ### end Alembic commands ###
